### PR TITLE
Remove scarab files from mapzen/ui

### PR DESCRIPTION
**Pull request by louh**
All scarab files are moved here: https://github.com/mapzen/scarab

### CODE REVIEW

**Comment by hanbyul-here** [comment]
wouldn't it make more sense to get rid of third party libraries from `readme`?

**Comment by louh** [comment]
We should eventually have our own checklist for maps and move that section to it...

**Comment by rmglennon** [comment]
There is this start to a checklist: https://github.com/mapzen/styleguide/blob/master/src/site/guides/maps.md

**Comment by louh** [comment]
Oh yeah, I started it! I was wondering where it went.
I'll move it, but otherwise, are we cool with the rest of this?

**Comment by hanbyul-here** [comment]
I will put a link for old mock up demo (since index page of repo does not exist).

**Pull request merged**
